import './globals.css'
import { Lato } from 'next/font/google'
import 'flowbite';

const fonts = Lato({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'LansPorto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fonts.className}>{children}</body>
    </html>
  )
}
